# Generated by Django 3.0.2 on 2020-02-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200223_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mobilenum',
            field=models.IntegerField(),
        ),
    ]
