# Generated by Django 3.0.2 on 2020-02-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200223_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier'),
            preserve_default=False,
        ),
    ]
