# Generated by Django 3.0.2 on 2020-01-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Bill',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='hotel_Main_Img',
            new_name='bill_Main_Img',
        ),
    ]
